language: go
sudo: required
services:
- docker
go:
- "1.13"
script:
- echo "Nginx ASG sync - commit:${TRAVIS_COMMIT}"
- make BUILD_IN_CONTAINER=0 all
before_install:
- echo "PR Slug:${TRAVIS_PULL_REQUEST_SLUG}"
- if [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "nginxinc/nginx-asg-sync" || "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  wget https://${fossalocation}/${fossafile} && tar xzf ${fossafile}
  && ./fossa init
  && FOSSA_API_KEY=${fossapush} ./fossa analyze -t nginx-asg-sync -b ${TRAVIS_BRANCH} ; fi
