name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *" # run every day at 01:30 UTC

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          stale-pr-message: "This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days."
          close-issue-message: "This issue was closed because it has been stalled for 7 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-all-pr-assignees: true
          operations-per-run: 100
